library(tmap)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(sf)
library(mapSpain)
library(units)
library(writexl)
library(purrr)
library(raster)
library(reshape2)
library(ggspatial)
library(tidyr)
library(biscale)
library(terra)
library(cowplot)
library(ggvenn)

setwd("~/GitHub/BiodiversityFacets")

####################################################################
############### Overlapping biodiversity facets############################

# clean environment
rm(list = ls())

# Adding Autonomous communities from Spain
AC <-esp_get_ccaa()
AC <- AC[!AC$iso2.ccaa.name.es %in% c("Canarias"),]
AC <- st_transform(AC, 25830) 

# load Spanish UTM grid
malla <- st_read("Spatial_Data/Malla_municipios/Malla10x10_Ter_p.shp")
malla <- st_transform(malla, 25830) 

###########Percentage of cells occupied by PV #################################
###################################################################################################
#Loading solar plants
solar <- st_read("Spatial_Data/Energy/allsolar_diss_April2025.shp")
solar <- st_transform(solar, 25830) 

#Loading TD, FD, PD data per cell
datosMAP <- st_read("Spatial_Data/3facets.shp")

# Intersecting solar plants polygons and cells with 3 biodiv facets 
PVint <- st_intersection(solar, datosMAP) 
PVint$area_int <- st_area(PVint)
PVint <- drop_units(PVint)
PVint$geometry <- NULL

length(unique(PVint$UTMCODE))

#Summing the total PV area per cell 
PVint1 <- PVint %>% 
  group_by(UTMCODE) %>% 
  summarize(PVarea_pcell = sum(area_int)) 

PVint1 <- merge(PVint, PVint1, by= "UTMCODE")
PVint1 <- PVint1 %>%
  distinct(UTMCODE, .keep_all = TRUE)

#Calculating the percentage of UTM area occupied by PV plants
PVint1$PercPV_cell <- PVint1$PVarea_pcell * 100 / PVint1$area_cell

PVint1_subset <- PVint1[, c("UTMCODE", "area_cell", "PVarea_pcell", "PercPV_cell")]

# Merging the dataframe with intersection data to the one with TD, FD, and PD
PVint11 <- merge(datosMAP, PVint1_subset, by = "UTMCODE", all.x = TRUE)

PVint2 <- PVint11[, c("UTMCODE","species", "SESFRic", "SESPD", "PercPV_cell")]

#Now I want to scale TD, FD, and PD in a range from 0-1 TO USE ZONATION SOFTWARE.
basic_function <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}
PVint2_1<-PVint2
PVint2_1$SESFRic <- basic_function(PVint2_1$SESFRic)
PVint2_1$SESPD <- basic_function(PVint2_1$SESPD)
PVint2_1$species <- basic_function(PVint2_1$species)
# Replacing NAs by 0 in PV occupancy cells
PVint2_1$PercPV_cell[is.na(PVint2_1$PercPV_cell)] <- 0
#Also scaling PV occupancy from 0-1. However, maximum occupancy % per cell is around 12%
PVint2_1$PercPV_cell0  <- PVint2_1$PercPV_cell #Keeping the PV percentage occupancy per cell before scaling 0-1
PVint2_1$PercPV_cell <- basic_function(PVint2_1$PercPV_cell)

# PV occupancy in tertiles
terciles <- quantile(PVint2$PercPV_cell, probs = c(0, 0.33, 0.67, 1), na.rm = TRUE)

# Creating the new column to show high, medium and low occupancy of PV plants inside each cell based on tertiles.
PVint2_1 <- PVint2_1 %>%
  mutate(PV_occupancy = cut(PercPV_cell, breaks = terciles, labels = c("low", "medium", "high"), include.lowest = TRUE))

write_sf(PVint2_1, "Spatial_Data/3facets_scaled_April25.shp")

facets <- st_read("Spatial_Data/3facets_scaled_April25.shp")

#################################################################
#####I rasterized TD, FD and PD in ArcMap, as it is slighltly more precise than R. Then each rasterized facet was used in Zonation 
#####to generate prioritized maps. For Zonation process I used the whole values not subsets of top values for each facet.
################################################################

#Using maps generated by Zonation 5 to generate Top 30% maps of each prioritization scenario (TD, FD, PD, TD+FD+PD)
#First using the map tht combines TD, FD, and PD
Hotsp_Zonation <- raster("Spatial_Data/Zonation/rankmap_hotsp.tif")

Hotsp_percentil30 <- quantile(Hotsp_Zonation, 0.7)
Hotsp_percentil17 <- quantile(Hotsp_Zonation, 0.83)
Hotsp_percentil10 <- quantile(Hotsp_Zonation, 0.9)
Hotsp_percentil5 <- quantile(Hotsp_Zonation, 0.95)

Hotsp_classes <- calc(Hotsp_Zonation, fun = function(x) {
  ifelse(x >= Hotsp_percentil5, 4,  # Top 5%
         ifelse(x >= Hotsp_percentil10, 3,  # Top 10%
                ifelse(x >= Hotsp_percentil17, 2,  # Top 17%
                       ifelse(x >= Hotsp_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("ivory2", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

# raster into data frame for ggplot
df <- as.data.frame(rasterToPoints(Hotsp_classes))
colnames(df) <- c("x", "y", "category")

#Loading ACs
comm <-esp_get_ccaa()
comm <- comm[!comm$iso2.ccaa.name.es %in% c("Canarias"),]
comm <- st_transform(comm, st_crs(Hotsp_Zonation))

TDFDPD <- ggplot() +
  geom_raster(data = df, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +  # Agregar límites de comunidades en gris claro
  scale_fill_manual(values = custom_colors, labels = categories, name = "Hotspot Level") +
  theme_minimal() +
  labs(title = "Hotspot Prioritization Levels",
       x = "Longitude",
       y = "Latitude") +
  theme(legend.position = "right")

ggsave("Figures/TDFDPD_tops.tiff", plot = TDFDPD, width = 10, height = 8, dpi = 300, compression = "lzw")

dev.off()

#Now the map that contains TD
TD_Zonation <- raster("Spatial_Data/Zonation/rankmap_TD.tif")

TD_percentil30 <- quantile(TD_Zonation, 0.7)
TD_percentil17 <- quantile(TD_Zonation, 0.83)
TD_percentil10 <- quantile(TD_Zonation, 0.9)
TD_percentil5 <- quantile(TD_Zonation, 0.95)

TD_classes <- calc(TD_Zonation, fun = function(x) {
  ifelse(x >= TD_percentil5, 4,  # Top 5%
         ifelse(x >= TD_percentil10, 3,  # Top 10%
                ifelse(x >= TD_percentil17, 2,  # Top 17%
                       ifelse(x >= TD_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("gray91", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

df1 <- as.data.frame(rasterToPoints(TD_classes))
colnames(df1) <- c("x", "y", "category")

TD <- ggplot() +
  geom_raster(data = df1, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "Taxonomic diversity",
       x = "Longitude",
       y = "Latitude") +
  theme(legend.position = "left")

ggsave("Figures/TD_tops.tiff", plot = TD, width = 10, height = 8, dpi = 300, compression = "lzw")

#Now the map that contains FD
FD_Zonation <- raster("Spatial_Data/Zonation/rankmap_FD.tif")

FD_percentil30 <- quantile(FD_Zonation, 0.7)
FD_percentil17 <- quantile(FD_Zonation, 0.83)
FD_percentil10 <- quantile(FD_Zonation, 0.9)
FD_percentil5 <- quantile(FD_Zonation, 0.95)

FD_classes <- calc(FD_Zonation, fun = function(x) {
  ifelse(x >= FD_percentil5, 4,  # Top 5%
         ifelse(x >= FD_percentil10, 3,  # Top 10%
                ifelse(x >= FD_percentil17, 2,  # Top 17%
                       ifelse(x >= FD_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("gray91", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

df2 <- as.data.frame(rasterToPoints(FD_classes))
colnames(df2) <- c("x", "y", "category")

FD <- ggplot() +
  geom_raster(data = df2, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "Functional diversity",
       x = "Longitude",
       y = "Latitude") +
  theme(legend.position = "left")
ggsave("Figures/FD_tops.tiff", plot = FD, width = 10, height = 8, dpi = 300, compression = "lzw")

#Now the map that contains PD
PD_Zonation <- raster("Spatial_Data/Zonation/rankmap_PD.tif")

PD_percentil30 <- quantile(PD_Zonation, 0.7)
PD_percentil17 <- quantile(PD_Zonation, 0.83)
PD_percentil10 <- quantile(PD_Zonation, 0.9)
PD_percentil5 <- quantile(PD_Zonation, 0.95)

PD_classes <- calc(PD_Zonation, fun = function(x) {
  ifelse(x >= PD_percentil5, 4,  # Top 5%
         ifelse(x >= PD_percentil10, 3,  # Top 10%
                ifelse(x >= PD_percentil17, 2,  # Top 17%
                       ifelse(x >= PD_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("gray91", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

df3 <- as.data.frame(rasterToPoints(PD_classes))
colnames(df3) <- c("x", "y", "category")

PD <- ggplot() +
  geom_raster(data = df3, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "Phylogenetic diversity",
       x = "Longitude",
       y = "Latitude") +
  theme(legend.position = "left")
ggsave("Figures/PD_tops.tiff", plot = PD, width = 10, height = 8, dpi = 300, compression = "lzw")

Hotsp_top30 <- calc(Hotsp_Zonation, fun = function(x) { ifelse(x >= Hotsp_percentil30, 1, 0) })
TD_top30 <- calc(TD_Zonation, fun = function(x) { ifelse(x >= TD_percentil30, 1, 0) })
FD_top30 <- calc(FD_Zonation, fun = function(x) { ifelse(x >= FD_percentil30, 1, 0) })
PD_top30 <- calc(PD_Zonation, fun = function(x) { ifelse(x >= PD_percentil30, 1, 0) })

# Raster into data frames for ggplot2
TD_df <- as.data.frame(as(TD_top30, "SpatialPixelsDataFrame"))
FD_df <- as.data.frame(as(FD_top30, "SpatialPixelsDataFrame"))
PD_df <- as.data.frame(as(PD_top30, "SpatialPixelsDataFrame"))
Hotsp_df <- as.data.frame(as(Hotsp_top30, "SpatialPixelsDataFrame"))

#I want to know the percentage of individual facet scenarios covered under all seven scenarios

# First we calculate for the TD scenario

# Obviously 100% of TD scenario is covered under the TD scenario
TD_overlap <- TD_top30 * TD_top30  # This creates an overlappin raster (1 = solapamiento)
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# Cover % for FD under the TD scenario
FD_overlap <- FD_top30 * TD_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# Cover % for PD under the TD scenario 
PD_overlap <- PD_top30 * TD_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 100%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 50.1%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 33.9%

# Now we calculate for the FD scenario

# Cover % of TD under the FD scenario
TD_overlap <- TD_top30 * FD_top30  
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# Cover % of FD under the FD scenario
FD_overlap <- FD_top30 * FD_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# Cover % of PD under the FD scenario
PD_overlap <- PD_top30 * FD_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 50.1%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 100%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 54.2%

# Now under the PD scenario
# Cover % of TD under the PD scenario
TD_overlap <- TD_top30 * PD_top30  
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# Cover % of FD under the PD scenario
FD_overlap <- FD_top30 * PD_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# Cover % of PD under the PD scenario
PD_overlap <- PD_top30 * PD_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 33.9%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 54.2%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 100%

# Now under the TD-FD-PD scenario
# TD coverage% under the TD-FD-PD scenario
TD_overlap <- TD_top30 * Hotsp_top30  
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# FD coverage% under the TD-FD-PD scenario
FD_overlap <- FD_top30 * Hotsp_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# PD coverage% under the TD-FD-PD scenario
PD_overlap <- PD_top30 * Hotsp_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 68.5%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 75.5%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 59.7%

#Now creating a bivariate map to intersect PV occupancy and Conservation value (given by the TD+FD+PD scenario).
# Crea un raster vacío (con resolución 10km en la proyección UTM 30N)
template_raster <- rast(ext(facets), resolution = 10000, crs = st_crs(facets)$wkt)

PV <- rasterize(vect(facets), template_raster, field = "PrcPV_c", fun = "mean")

crs_25830 <- "EPSG:25830"

Hotsp_Zonation <- project(Hotsp_Zonation, crs_25830)
PV <- project(PV, crs_25830)

Hotsp_Zonation <- resample(Hotsp_Zonation, PV, method = "bilinear")

# Combining rasters in one dataframe
dataf <- as.data.frame(Hotsp_Zonation, xy = TRUE)

pv_df <- as.data.frame(PV, xy = TRUE)
dataf$PV <- pv_df$PrcPV_c  # Asegúrate de asignar solo la columna PrcPV_c

print(class(dataf$PV))  # Debería ser "numeric"

dataf <- dataf %>%
  rename(Conservation = names(Hotsp_Zonation), PV = PV) %>%
  drop_na()

print(class(dataf$Conservation))
print(class(dataf$PV))

# PV in "Low", "Medium", "High" [0, 0.33, 0.67, 1]
dataf <- dataf %>%
  mutate(PV_cat = cut(PV, 
                      breaks = c(-1e-10, 0.33, 0.67, 1), 
                      labels = c("Low", "Medium", "High"), 
                      include.lowest = TRUE)) %>%
  mutate(PV_cat = if_else(PV == 0, "Low", as.character(PV_cat)),  # Asegurar que PV = 0 sea "Low"
         PV_cat = factor(PV_cat, levels = c("Low", "Medium", "High")))

print(table(dataf$PV_cat))

print(class(dataf$PV_cat))  # Debería ser "factor"

# Calculating quantiles only for cells with values different from 0. Quantiles categorization using also cells 0 leads to inaccurate. 
# Too many cells where PV does not exist.  
non_zero_pv <- dataf$PV[dataf$PV > 0]
quantiles <- quantile(non_zero_pv, probs = c(0, 0.33, 0.67, 1))

# breaks based on quantiles of values different from 0
breaks <- c(-1e-10, quantiles[2], quantiles[3], quantiles[4])

# PV in "Low", "Medium", "High" using only values different from 0. 
dataf <- dataf %>%
  mutate(PV_cat = cut(PV, 
                      breaks = breaks, 
                      labels = c("Low", "Medium", "High"), 
                      include.lowest = TRUE)) %>%
  mutate(PV_cat = if_else(PV == 0, "Low", as.character(PV_cat)),  # Asegurar que PV = 0 sea "Low"
         PV_cat = factor(PV_cat, levels = c("Low", "Medium", "High")))

print(table(dataf$PV_cat))

print(class(dataf$PV_cat))  

dataf <- bi_class(dataf, x = Conservation, y = PV_cat, style = "equal", dim = 3)

dataf_sf <- st_as_sf(dataf, coords = c("x", "y"), crs = 25830)

map <- ggplot() +
  geom_sf(data = AC, fill = "gray95", color = "gray80") +  # Mapa de fondo
  geom_tile(data = dataf, aes(x = x, y = y, fill = bi_class)) +  # sin bordes
  bi_scale_fill(pal = "PurpleGrn", dim = 3) +  # Estilo de color
  theme_minimal() +
  theme(legend.position = "none") +  # Ocultar leyenda por defecto
  geom_sf(data = AC, fill = NA, color = "black", linewidth = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "grid", 
                         pad_x = unit(0, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering())

legend <- bi_legend(
  pal = "PurpleGrn",
  dim = 3,
  xlab = "Cons. value",
  ylab = "PV",
  size = 10  
)

PVconflict <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +  # El mapa ocupa todo el espacio
  draw_plot(legend, x = 0.72, y = 0.25, width = 0.3, height = 0.15)  # Ajusté la posición y aumenté el tamaño

plot(PVconflict)

ggsave("Figures/Conflict_April25.tiff", PVconflict, wi = 20, he = 20, un = "cm", dpi = 300)

# Generating a map only for conflict cells, i.e., "3-3" in the column "biclass", which represent high cons value and high PV ocuppancy
dataf_3_3 <- dataf %>%
  filter(bi_class == "3-3")

map_3_3 <- ggplot() +
  geom_sf(data = AC, fill = "gray95", color = "gray80") +  # Mapa de fondo
  geom_tile(data = dataf_3_3, aes(x = x, y = y, fill = bi_class)) +  
  bi_scale_fill(pal = "PurpleGrn", dim = 3) +  
  theme_minimal() +
  theme(legend.position = "none") +  
  geom_sf(data = AC, fill = NA, color = "black", linewidth = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "grid", 
                         pad_x = unit(0, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering())

print(map_3_3)

ggsave("Figures/3_3_Conservation_PV_April25.tiff", map_3_3, wi = 20, he = 20, un = "cm", dpi = 300)
