library(tmap)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(sf)
library(mapSpain)
library(units)
library(writexl)
library(purrr)
library(raster)
library(reshape2)
library(ggspatial)
library(tidyr)
library(biscale)
library(terra)
library(cowplot)
library(ggvenn)

setwd("~/GitHub/BiodiversityFacets")

####################################################################
############### Overlapping biodiversity facets############################

# clean environment
rm(list = ls())

# Adding Autonomous communities from Spain
AC <-esp_get_ccaa()
AC <- AC[!AC$iso2.ccaa.name.es %in% c("Canarias"),]
AC <- st_transform(AC, 25830) 

# load Spanish UTM grid
malla <- st_read("Spatial_Data/Malla_municipios/Malla10x10_Ter_p.shp")
malla <- st_transform(malla, 25830) 

###########Percentage of cells occupied by PV #################################
###################################################################################################
#Loading solar plants
solar <- st_read("Spatial_Data/Energy/allsolar_diss_April2025.shp")
solar <- st_transform(solar, 25830) 

#Loading TD, FD, PD data per cell
datosMAP <- st_read("Spatial_Data/3facets.shp")

# Intersecting solar plants polygons and cells with 3 biodiv facets 
PVint <- st_intersection(solar, datosMAP) 
PVint$area_int <- st_area(PVint)
PVint <- drop_units(PVint)
PVint$geometry <- NULL

length(unique(PVint$UTMCODE))

#Summing the total PV area per cell 
PVint1 <- PVint %>% 
  group_by(UTMCODE) %>% 
  summarize(PVarea_pcell = sum(area_int)) 

PVint1 <- merge(PVint, PVint1, by= "UTMCODE")
PVint1 <- PVint1 %>%
  distinct(UTMCODE, .keep_all = TRUE)

#Calculating the percentage of UTM area occupied by PV plants
PVint1$PercPV_cell <- PVint1$PVarea_pcell * 100 / PVint1$area_cell

PVint1_subset <- PVint1[, c("UTMCODE", "area_cell", "PVarea_pcell", "PercPV_cell")]

# Merging the dataframe with intersection data to the one with TD, FD, and PD
PVint11 <- merge(datosMAP, PVint1_subset, by = "UTMCODE", all.x = TRUE)

PVint2 <- PVint11[, c("UTMCODE","species", "SESFRic", "SESPD", "PercPV_cell")]

#Now I want to scale TD, FD, and PD in a range from 0-1 TO USE ZONATION SOFTWARE.
basic_function <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}
PVint2_1<-PVint2
PVint2_1$SESFRic <- basic_function(PVint2_1$SESFRic)
PVint2_1$SESPD <- basic_function(PVint2_1$SESPD)
PVint2_1$species <- basic_function(PVint2_1$species)
# Replacing NAs by 0 in PV occupancy cells
PVint2_1$PercPV_cell[is.na(PVint2_1$PercPV_cell)] <- 0
#Also scaling PV occupancy from 0-1. However, maximum occupancy % per cell is around 12%
PVint2_1$PercPV_cell0  <- PVint2_1$PercPV_cell #Keeping the PV percentage occupancy per cell before scaling 0-1
PVint2_1$PercPV_cell <- basic_function(PVint2_1$PercPV_cell)

# PV occupancy in tertiles
terciles <- quantile(PVint2$PercPV_cell, probs = c(0, 0.33, 0.67, 1), na.rm = TRUE)

# Creating the new column to show high, medium and low occupancy of PV plants inside each cell based on tertiles.
PVint2_1 <- PVint2_1 %>%
  mutate(PV_occupancy = cut(PercPV_cell, breaks = terciles, labels = c("low", "medium", "high"), include.lowest = TRUE))

write_sf(PVint2_1, "Spatial_Data/3facets_scaled_April25.shp")

facets <- st_read("Spatial_Data/3facets_scaled_April25.shp")

#################################################################
#####I rasterized TD, FD and PD in ArcMap, then each rasterized facet was used in Zonation 
#####to generate prioritized maps. For Zonation process I used the whole values not subsets of top values for each facet.
################################################################

#Using maps generated by Zonation 5 to generate Top 30% maps of each prioritization scenario (TD, FD, PD, TD+FD+PD)
#First using the map that combines TD, FD, and PD
Hotsp_Zonation <- raster("Spatial_Data/Zonation/rankmap_hotsp.tif")

Hotsp_percentil30 <- quantile(Hotsp_Zonation, 0.7)
Hotsp_percentil17 <- quantile(Hotsp_Zonation, 0.83)
Hotsp_percentil10 <- quantile(Hotsp_Zonation, 0.9)
Hotsp_percentil5 <- quantile(Hotsp_Zonation, 0.95)

Hotsp_classes <- calc(Hotsp_Zonation, fun = function(x) {
  ifelse(x >= Hotsp_percentil5, 4,  # Top 5%
         ifelse(x >= Hotsp_percentil10, 3,  # Top 10%
                ifelse(x >= Hotsp_percentil17, 2,  # Top 17%
                       ifelse(x >= Hotsp_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("ivory2", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

# raster into data frame for ggplot
df <- as.data.frame(rasterToPoints(Hotsp_classes))
colnames(df) <- c("x", "y", "category")

#Loading ACs
comm <-esp_get_ccaa()
comm <- comm[!comm$iso2.ccaa.name.es %in% c("Canarias"),]
comm <- st_transform(comm, st_crs(Hotsp_Zonation))

TDFDPD <- ggplot() +
  geom_raster(data = df, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +  
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "TD + FD + PD",
       x = "Longitude",
       y = "Latitude") +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),  
        legend.position = "right")  

ggsave("Figures/TDFDPD_tops.tiff", plot = TDFDPD, width = 10, height = 8, dpi = 400, compression = "lzw")

#Now the map that contains TD
TD_Zonation <- raster("Spatial_Data/Zonation/rankmap_TD.tif")

TD_percentil30 <- quantile(TD_Zonation, 0.7)
TD_percentil17 <- quantile(TD_Zonation, 0.83)
TD_percentil10 <- quantile(TD_Zonation, 0.9)
TD_percentil5 <- quantile(TD_Zonation, 0.95)

TD_classes <- calc(TD_Zonation, fun = function(x) {
  ifelse(x >= TD_percentil5, 4,  # Top 5%
         ifelse(x >= TD_percentil10, 3,  # Top 10%
                ifelse(x >= TD_percentil17, 2,  # Top 17%
                       ifelse(x >= TD_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("gray91", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

df1 <- as.data.frame(rasterToPoints(TD_classes))
colnames(df1) <- c("x", "y", "category")

TD <- ggplot() +
  geom_raster(data = df1, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "Taxonomic Diversity (TD)",
       x = "Longitude",
       y = "Latitude") +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),  
        legend.position = "none")                

ggsave("Figures/TD_tops.tiff", plot = TD, width = 10, height = 8, dpi = 400, compression = "lzw")

#Now the map that contains FD
FD_Zonation <- raster("Spatial_Data/Zonation/rankmap_FD.tif")

FD_percentil30 <- quantile(FD_Zonation, 0.7)
FD_percentil17 <- quantile(FD_Zonation, 0.83)
FD_percentil10 <- quantile(FD_Zonation, 0.9)
FD_percentil5 <- quantile(FD_Zonation, 0.95)

FD_classes <- calc(FD_Zonation, fun = function(x) {
  ifelse(x >= FD_percentil5, 4,  # Top 5%
         ifelse(x >= FD_percentil10, 3,  # Top 10%
                ifelse(x >= FD_percentil17, 2,  # Top 17%
                       ifelse(x >= FD_percentil30, 1, 0))))  # Top 30% 
})

custom_colors <- c("gray91", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

df2 <- as.data.frame(rasterToPoints(FD_classes))
colnames(df2) <- c("x", "y", "category")

FD <- ggplot() +
  geom_raster(data = df2, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "Functional diversity(FD)",
       x = "Longitude",
       y = "Latitude") +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),  
                              legend.position = "none")  

ggsave("Figures/FD_tops.tiff", plot = FD, width = 10, height = 8, dpi = 400, compression = "lzw")

#Now the map that contains PD
PD_Zonation <- raster("Spatial_Data/Zonation/rankmap_PD.tif")

PD_percentil30 <- quantile(PD_Zonation, 0.7)
PD_percentil17 <- quantile(PD_Zonation, 0.83)
PD_percentil10 <- quantile(PD_Zonation, 0.9)
PD_percentil5 <- quantile(PD_Zonation, 0.95)

PD_classes <- calc(PD_Zonation, fun = function(x) {
  ifelse(x >= PD_percentil5, 4,  # Top 5%
         ifelse(x >= PD_percentil10, 3,  # Top 10%
                ifelse(x >= PD_percentil17, 2,  # Top 17%
                       ifelse(x >= PD_percentil30, 1, 0))))  # Top 30% y fondo
})

custom_colors <- c("gray91", "yellow", "pink", "orange", "red") 
categories <- c("Below 30%", "Top 30%", "Top 17%", "Top 10%", "Top 5%")

df3 <- as.data.frame(rasterToPoints(PD_classes))
colnames(df3) <- c("x", "y", "category")

PD <- ggplot() +
  geom_raster(data = df3, aes(x = x, y = y, fill = factor(category))) +
  geom_sf(data = comm, fill = NA, color = "gray", linewidth = 0.5) +
  scale_fill_manual(values = custom_colors, labels = categories, name = "") +
  theme_minimal() +
  labs(title = "Phylogenetic diversity",
       x = "Longitude",
       y = "Latitude") +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),  
        legend.position = "none")  

ggsave("Figures/PD_tops.tiff", plot = PD, width = 10, height = 8, dpi = 400, compression = "lzw")

Hotsp_top30 <- calc(Hotsp_Zonation, fun = function(x) { ifelse(x >= Hotsp_percentil30, 1, 0) })
TD_top30 <- calc(TD_Zonation, fun = function(x) { ifelse(x >= TD_percentil30, 1, 0) })
FD_top30 <- calc(FD_Zonation, fun = function(x) { ifelse(x >= FD_percentil30, 1, 0) })
PD_top30 <- calc(PD_Zonation, fun = function(x) { ifelse(x >= PD_percentil30, 1, 0) })

# Raster into data frames for ggplot2
TD_df <- as.data.frame(as(TD_top30, "SpatialPixelsDataFrame"))
FD_df <- as.data.frame(as(FD_top30, "SpatialPixelsDataFrame"))
PD_df <- as.data.frame(as(PD_top30, "SpatialPixelsDataFrame"))
Hotsp_df <- as.data.frame(as(Hotsp_top30, "SpatialPixelsDataFrame"))

#I want to know the percentage of individual facet scenarios covered under all seven scenarios

# First we calculate for the TD scenario

# Obviously 100% of TD scenario is covered under the TD scenario
TD_overlap <- TD_top30 * TD_top30  # This creates an overlappin raster (1 = solapamiento)
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# Cover % for FD under the TD scenario
FD_overlap <- FD_top30 * TD_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# Cover % for PD under the TD scenario 
PD_overlap <- PD_top30 * TD_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 100%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 50.1%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 33.9%

# Now we calculate for the FD scenario

# Cover % of TD under the FD scenario
TD_overlap <- TD_top30 * FD_top30  
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# Cover % of FD under the FD scenario
FD_overlap <- FD_top30 * FD_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# Cover % of PD under the FD scenario
PD_overlap <- PD_top30 * FD_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 50.1%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 100%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 54.2%

# Now under the PD scenario
# Cover % of TD under the PD scenario
TD_overlap <- TD_top30 * PD_top30  
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# Cover % of FD under the PD scenario
FD_overlap <- FD_top30 * PD_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# Cover % of PD under the PD scenario
PD_overlap <- PD_top30 * PD_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 33.9%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 54.2%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 100%

# Now under the TD-FD-PD scenario
# TD coverage% under the TD-FD-PD scenario
TD_overlap <- TD_top30 * Hotsp_top30  
TD_coverage <- cellStats(TD_overlap, sum) / cellStats(TD_top30, sum) * 100

# FD coverage% under the TD-FD-PD scenario
FD_overlap <- FD_top30 * Hotsp_top30
FD_coverage <- cellStats(FD_overlap, sum) / cellStats(FD_top30, sum) * 100

# PD coverage% under the TD-FD-PD scenario
PD_overlap <- PD_top30 * Hotsp_top30
PD_coverage <- cellStats(PD_overlap, sum) / cellStats(PD_top30, sum) * 100

# Results
cat("Cobertura relativa de TD:", TD_coverage, "%\n") # 68.5%
cat("Cobertura relativa de FD:", FD_coverage, "%\n") # 75.5%
cat("Cobertura relativa de PD:", PD_coverage, "%\n") # 59.7%

#Now creating a bivariate map to intersect PV occupancy and Conservation value (given by the TD+FD+PD scenario).
template_raster <- rast(ext(facets), resolution = 10000, crs = st_crs(facets)$wkt)

PV <- rasterize(vect(facets), template_raster, field = "PrcPV_c", fun = "mean")

crs_25830 <- "EPSG:25830"

Hotsp_Zonation <- rast(Hotsp_Zonation)
Hotsp_Zonation <- project(Hotsp_Zonation, crs_25830)
PV <- project(PV, crs_25830)

Hotsp_Zonation <- resample(Hotsp_Zonation, PV, method = "bilinear")

# Combining rasters in one dataframe
dataf <- as.data.frame(Hotsp_Zonation, xy = TRUE)

pv_df <- as.data.frame(PV, xy = TRUE)
dataf$PV <- pv_df$PrcPV_c  

print(class(dataf$PV)) 

dataf <- dataf %>%
  rename(Conservation = names(Hotsp_Zonation), PV = PV) %>%
  drop_na()

print(class(dataf$Conservation))
print(class(dataf$PV))

# Calculating quantiles only for cells with values different from 0. Quantiles categorization using also cells 0 leads to inaccurate. 
# Too many cells where PV does not exist.  
non_zero_pv <- dataf$PV[dataf$PV > 0]
quantiles <- quantile(non_zero_pv, probs = c(0, 0.33, 0.67, 1))

# breaks based on quantiles of values different from 0
breaks <- c(-1e-10, quantiles[2], quantiles[3], quantiles[4])

# PV in "Low", "Medium", "High" using only values different from 0. 
dataf <- dataf %>%
  mutate(PV_cat = cut(PV, 
                      breaks = breaks, 
                      labels = c("Low", "Medium", "High"), 
                      include.lowest = TRUE)) %>%
  mutate(PV_cat = if_else(PV == 0, "Low", as.character(PV_cat)),  # PV = 0 is included in "Low"
         PV_cat = factor(PV_cat, levels = c("Low", "Medium", "High")))

print(table(dataf$PV_cat))

print(class(dataf$PV_cat))  

dataf <- bi_class(dataf, x = Conservation, y = PV_cat, style = "equal", dim = 3)

dataf_sf <- st_as_sf(dataf, coords = c("x", "y"), crs = 25830)

map <- ggplot() +
  geom_sf(data = AC, fill = "gray95", color = "gray80") + 
  geom_tile(data = dataf, aes(x = x, y = y, fill = bi_class)) + 
  bi_scale_fill(pal = "PurpleGrn", dim = 3) + 
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),  
    axis.title.y = element_blank()   
  ) + 
  geom_sf(data = AC, fill = NA, color = "black", linewidth = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "grid", 
                         pad_x = unit(0, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering()) +
  annotation_scale(location = "bl", width_hint = 0.3)  

legend <- bi_legend(
  pal = "PurpleGrn",
  dim = 3,
  xlab = "Cons. value",
  ylab = "PV",
  size = 12  
)

Bivar <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +  
  draw_plot(legend, x = 0.65, y = 0.2, width = 0.31, height = 0.21)  

plot(Bivar)

map <- ggplot() +
  geom_sf(data = AC, fill = "gray95", color = "gray80") + 
  geom_tile(data = dataf, aes(x = x, y = y, fill = bi_class)) + 
  bi_scale_fill(pal = "PurpleGrn", dim = 3) + 
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),  
    axis.title.y = element_blank()   
  ) + 
  geom_sf(data = AC, fill = NA, color = "black", linewidth = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "grid", 
                         pad_x = unit(0, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering())+
  annotation_scale(location = "bl", width_hint = 0.3)  

legend <- bi_legend(
  pal = "PurpleGrn",
  dim = 3,
  xlab = "Cons. value",
  ylab = "PV",
  size = 14  
)

Bivar <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +  
  draw_plot(legend, x = 0.72, y = 0.25, width = 0.3, height = 0.15) 

plot(Bivar)

ggsave("Figures/Bivar_April25.tiff", Bivar, wi = 20, he = 20, un = "cm", dpi = 300)

# Generating a map only for conflict cells, i.e., "3-3" in the column "biclass", which represents high cons value and high PV occupancy
dataf_3_3 <- dataf %>%
  filter(bi_class == "3-3")

# Creating the map
map_3_3 <- ggplot() +
  geom_sf(data = AC, fill = "gray95", color = "gray80") +
  geom_tile(data = dataf_3_3, aes(x = x, y = y), fill = "#011a1d") +  
  labs(title = "Exposure areas") +  
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),  
    axis.title.y = element_blank(),  
    plot.title = element_text(hjust = 0.5, size = 18, face = "bold")  
  ) +
  geom_sf(data = AC, fill = NA, color = "black", linewidth = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "grid", 
                         pad_x = unit(0, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering()) +
  annotation_scale(location = "bl", width_hint = 0.3)

print(map_3_3)
ggsave("Figures/3_3_Conflict_April25.tiff", map_3_3, wi = 20, he = 20, un = "cm", dpi = 300)

# Filtering the 3-1 cells (high conservation value + low PV)
dataf_3_1 <- dataf %>%
  filter(bi_class == "3-1")

# Creating the map
map_3_1 <- ggplot() +
  geom_sf(data = AC, fill = "gray95", color = "gray80") +
  geom_tile(data = dataf_3_1, aes(x = x, y = y), fill = "#027a2e") +
  labs(title = "No-go areas") + 
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(),  
    plot.title = element_text(hjust = 0.5, size = 18, face = "bold")  
  ) +
  geom_sf(data = AC, fill = NA, color = "black", linewidth = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "grid", 
                         pad_x = unit(0, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering()) +
  annotation_scale(location = "bl", width_hint = 0.3)

print(map_3_1)

ggsave("Figures/3_1_Nogo_April25.tiff", map_3_1, wi = 20, he = 20, un = "cm", dpi = 300)

#Now I want to correlate conservation value and a combined index of threat categories (this is based on SCPTS, SPEC and EPS
#lists used in Medrano-Vizcaíno, et al. (2025). Spatial shifts in steppe bird hotspots over two decades: Assessing conservation priorities and the role of protected areas. Biological Conservation, 305, 111068.
Conserv.value  <- Hotsp_Zonation
Threats <- read.csv("Data/Species_and_threats.csv")

# Scalating SCPTS from 0 to 10 as the other threat status.
Threats$SCPTS <- (Threats$SCPTS.2023.value  - min(Threats$SCPTS.2023.value )) * (10 - 0) / (max(Threats$SCPTS.2023.value ) - min(Threats$SCPTS.2023.value )) + 0

#Merging with spatial data 
Threats <- left_join(malla[, "UTMCODE"], Threats,
                             by = "UTMCODE")

# Reprojecting raster
Conserv.value <- project(Conserv.value, "EPSG:25830")

# Reprojecting vectorial
Threats <- st_transform(Threats, crs = 25830)

crs(Conserv.value)
st_crs(Threats)

# Aggregating indexes values per UTM 
Threats0 <- aggregate(cbind(SCPTS, SPEC_VAL_2023, EPS_VAL_2023) ~ UTMCODE, data = Threats, FUN = sum)

#min max linear rescaling
basic_function <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}

# Apply the rescaling function to each relevant variable 
Threats0$SCPTS <- basic_function(Threats0$SCPTS)
Threats0$EPS <- basic_function(Threats0$EPS_VAL_2023)
Threats0$SPEC <- basic_function(Threats0$SPEC_VAL_2023)

# Summing scaled values to create a new combined index
Threats0$comb_ind <- rowSums(Threats0[, c("SCPTS", "EPS", "SPEC")], na.rm = TRUE)

Threats0$comb_ind_scaled <- basic_function(Threats0$comb_ind)


#Merging with spatial data of 10 x 10 km cellgrid 
Threats1 <- left_join(malla[, "UTMCODE"], Threats0,
                             by = "UTMCODE")

# Extracting cons values from the raster (TD+FD+PD scenario) to the vectorial polygons
Threats1$cons.value <- terra::extract(Conserv.value, vect(Threats1), fun = mean, na.rm = TRUE)[,2]

# Removing NA cells
datos_cor <- Threats1[, c("comb_ind_scaled", "cons.value")]
datos_cor <- na.omit(datos_cor)

cor_test <- cor.test(datos_cor$comb_ind_scaled, datos_cor$cons.value, method = "pearson")

r_val <- round(cor_test$estimate, 1)

Corr_plot <- ggplot(datos_cor, aes(x = comb_ind_scaled, y = cons.value)) +
  geom_point(alpha = 0.6, color = "darkgreen") +
  geom_smooth(method = "lm", se = TRUE, color = "lightgrey", linetype = "dashed") +
  annotate("text", x = Inf, y = -Inf, hjust = 1.1, vjust = -1.2,
           label = paste0("r = ", r_val),
           size = 5, fontface = "italic", color = "black") +
  labs(
    title = "",
    x = "Threat level (combined index)",
    y = "Conservation value"
  ) +
  theme_minimal()
plot(Corr_plot)
ggsave("Figures/correlationThreatvsCons.png", plot = Corr_plot, width = 8, height = 6, dpi = 300)

#Now lets see how correlated is threat level with TD scenario

# Reprojecting raster
TD_Zonation <- rast(TD_Zonation)
TD_Zonation <- project(TD_Zonation, "EPSG:25830")

crs(TD_Zonation)
st_crs(Threats)

# Extracting cons values from the raster (TD scenario) to the vectorial polygons
Threats1$TD <- terra::extract(TD_Zonation, vect(Threats1), fun = mean, na.rm = TRUE)[,2]

# Removing NA cells
datos_corTD <- Threats1[, c("comb_ind_scaled", "TD")]
datos_corTD <- na.omit(datos_corTD)

cor_testTD <- cor.test(datos_corTD$comb_ind_scaled, datos_corTD$TD, method = "pearson")

r_val <- round(cor_testTD$estimate, 1)

Corr_plotTD <- ggplot(datos_corTD, aes(x = comb_ind_scaled, y = TD)) +
  geom_point(alpha = 0.6, color = "darkgreen") +
  geom_smooth(method = "lm", se = TRUE, color = "lightgrey", linetype = "dashed") +
  annotate("text", x = Inf, y = -Inf, hjust = 1.1, vjust = -1.2,
           label = paste0("r = ", r_val),
           size = 5, fontface = "italic", color = "black") +
  labs(
    title = "",
    x = "Threat level (combined index))",
    y = "TD value"
  ) +
  theme_minimal()
plot(Corr_plotTD)

#Now lets see how correlated is threat level with FD scenario

# Reprojecting raster
FD_Zonation <- rast(FD_Zonation)
FD_Zonation <- project(FD_Zonation, "EPSG:25830")

crs(FD_Zonation)
st_crs(Threats)

# Extracting cons values from the raster (FD scenario) to the vectorial polygons
Threats1$FD <- terra::extract(FD_Zonation, vect(Threats1), fun = mean, na.rm = TRUE)[,2]

# Removing NA cells
datos_corFD <- Threats1[, c("comb_ind_scaled", "FD")]
datos_corFD <- na.omit(datos_corFD)

cor_testFD <- cor.test(datos_corFD$comb_ind_scaled, datos_corFD$FD, method = "pearson")

r_val <- round(cor_testFD$estimate, 1)

Corr_plotFD <- ggplot(datos_corFD, aes(x = comb_ind_scaled, y = FD)) +
  geom_point(alpha = 0.6, color = "darkgreen") +
  geom_smooth(method = "lm", se = TRUE, color = "lightgrey", linetype = "dashed") +
  annotate("text", x = Inf, y = -Inf, hjust = 1.1, vjust = -1.2,
           label = paste0("r = ", r_val),
           size = 5, fontface = "italic", color = "black") +
  labs(
    title = "",
    x = "Threat level (combined index))",
    y = "FD value"
  ) +
  theme_minimal()
plot(Corr_plotFD)

#Now lets see how correlated is threat level with PD scenario
# Reprojecting raster
PD_Zonation <- rast(PD_Zonation)
PD_Zonation <- project(PD_Zonation, "EPSG:25830")

crs(PD_Zonation)
st_crs(Threats)

# Extracting cons values from the raster (PD scenario) to the vectorial polygons
Threats1$PD <- terra::extract(PD_Zonation, vect(Threats1), fun = mean, na.rm = TRUE)[,2]

# Removing NA cells
datos_corPD <- Threats1[, c("comb_ind_scaled", "PD")]
datos_corPD <- na.omit(datos_corPD)

cor_testPD <- cor.test(datos_corPD$comb_ind_scaled, datos_corPD$PD, method = "pearson")

r_val <- round(cor_testPD$estimate, 1)

Corr_plotPD <- ggplot(datos_corPD, aes(x = comb_ind_scaled, y = PD)) +
  geom_point(alpha = 0.6, color = "darkgreen") +
  geom_smooth(method = "lm", se = TRUE, color = "lightgrey", linetype = "dashed") +
  annotate("text", x = Inf, y = -Inf, hjust = 1.1, vjust = -1.2,
           label = paste0("r = ", r_val),
           size = 5, fontface = "italic", color = "black") +
  labs(
    title = "",
    x = "Threat level (combined index))",
    y = "PD value"
  ) +
  theme_minimal()
plot(Corr_plotPD)

template_raster1 <- raster(extent(Threats1), resolution = 10000, crs = st_crs(Threats1)$proj4string)

Threatindex <- rasterize(as(Threats1, "Spatial"), template_raster1, field = "comb_ind_scaled", fun = "mean")

crs_25830 <- "+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs"

# Reproject both rasters to EPSG:25830
Threatindex <- projectRaster(Threatindex, crs = crs_25830)

# Calculate the 70th percentile to select the top 30%
top_30_threshold <- quantile(Threats1$comb_ind_scaled, 0.7, na.rm = TRUE)

# Filter the data for the top 30% (values greater than the 70th percentile)
Threats1_top30 <- Threats1 %>% filter(comb_ind_scaled > top_30_threshold)

raster_resolution <- 10000  

# Creating a  raster object with the same extension as vectorial layer
r <- raster(extent(Threats1_top30), resolution = c(raster_resolution, raster_resolution))

# Rasterizing the vectorial layer of the top 30% values
Threat_top30 <- rasterize(as(Threats1_top30, "Spatial"), r, field = "comb_ind_scaled", fun = "mean")
# Threatened species coverage % under the TD-FD-PD scenario
# Aligning Hotsp_top30 with Threat_top30
Hotsp_top30 <- resample(Hotsp_top30, Threat_top30, method = "ngb")
Threat_overlap <- Threat_top30 * Hotsp_top30  
Threat_coverage <- cellStats(Threat_overlap, sum) / cellStats(Threat_top30, sum) * 100
Threat_coverage <- cellStats(Threat_overlap, "sum", na.rm = TRUE) / cellStats(Threat_top30, "sum", na.rm = TRUE) * 100

# Threatened species coverage % under the TD-FD-PD scenario
TD_top30 <- resample(TD_top30, Threat_top30, method = "ngb")
Threat_overlapTD <- Threat_top30 * TD_top30  
Threat_coverageTD <- cellStats(Threat_overlapTD, "sum", na.rm = TRUE) / cellStats(Threat_top30, "sum", na.rm = TRUE) * 100

FD_top30 <- resample(FD_top30, Threat_top30, method = "ngb")
Threat_overlapFD <- Threat_top30 * FD_top30  
Threat_coverageFD <- cellStats(Threat_overlapFD, "sum", na.rm = TRUE) / cellStats(Threat_top30, "sum", na.rm = TRUE) * 100

PD_top30 <- resample(PD_top30, Threat_top30, method = "ngb")
Threat_overlapPD <- Threat_top30 * PD_top30  
Threat_coveragePD <- cellStats(Threat_overlapPD, "sum", na.rm = TRUE) / cellStats(Threat_top30, "sum", na.rm = TRUE) * 100

# Threatened species score covered under each scenario
cat("Cobertura relativa de Threatened under TD+FD+PD:", Threat_coverage, "%\n") # 62.8% under the TD+FD+PD
cat("Cobertura relativa de Threatened under TD:", Threat_coverageTD, "%\n") # 73.3%
cat("Cobertura relativa de Threatened under FD:", Threat_coverageFD, "%\n") # 49.4%
cat("Cobertura relativa de Threatened under PD:", Threat_coveragePD, "%\n") # 37.1%
